"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'robin'

#         

format = """$directory"""
right_format = """
$kubernetes\
$git_branch\
[](fg:color_purple)
$time\
[](fg:color_purple)
"""

[directory]
style = "fg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = true

[kubernetes]
style = "fg:color_green italic"
format = "[ $context]($style)"
disabled = false

[[kubernetes.contexts]]
context_pattern = "dev-gcp"
style = "fg:color_green italic"

[[kubernetes.contexts]]
context_pattern = "prod-gcp"
style = "fg:color_red italic"

[git_branch]
# symbol = ""
style = "fg:color_blue italic"
format = '[ $branch ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_purple inverted"
format = '[$time]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[palettes.robin]
color_blue = '#458588'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'


